### ISSUE TITLE
possibilité de découper des registres dans les macros (exemple)

### ISSUE THREAD

**Issue by EdouardBERGE** [sikorama/rasm-doc#2]
macro add16,acc,ajout

ld a,{acc}.low ; récupère le C de BC, ou le E de DE, ...
add {ajout}.low
ld {acc}.low,a
ld a,{acc}.high
adc {ajout}.high
ld {acc}.high,a

mend

add16 bc,hl

**Comment by sikorama** [comment]
macro add16, R1, R2

ld A,{R1}.low ; récupère le C de BC, ou le E de DE, ...
add {R2}.low
ld {R1}.low,A

ld A,{R1}.high
adc {R2}.high
ld {R1}.high,A

mend

add16 bc,hl
