### ISSUE TITLE
option -amper (ampersans) pour pouvoir utiliser le symbole & pour l'hexa

### ISSUE THREAD

**Issue by EdouardBERGE** [sikorama/rasm-doc#3]
ça s'utilise en conjonction avec l'option maxam, tous les symboles & hors chaines sont remplacés par un # 
on ne peut donc pas utiliser à la fois & pour l'hexa et pour le AND
option de compilation => -amper

**Comment by sikorama** [comment]
ok j'ajoute l'option d'invocation de rasm '-amper' qui permet de considerer & comme un prefixe pour spécifier les valeurs hexadecimales dans les expressions, en plus de #
