### ISSUE TITLE
caractères échapés pour le DEFB

### ISSUE THREAD

**Issue by EdouardBERGE** [sikorama/rasm-doc#9]
en déclaration de chaine, on peut faire des caractères de contrôle avec l'antisliash (comme en C)

   tab vertical                                                     case 'v':___output(ae,'\v');break;
saut de page                                                        case 'f':___output(ae,'\f');break;
zéro                                                        case '0':___output(ae,'\0');break;
retour à la ligne                                                        case 'r':___output(ae,'\r');break; 
CR                                                        case 'n':___output(ae,'\n');break;
tab                                                        case 't':___output(ae,'\t');break;

est-ce que ça vaut le coup que j'en ajoute?

je vois le \e pour 0x1B ou le \a pour 0x07, le \b en 0x08 qui manquent

dis moi :)

**Comment by EdouardBERGE** [comment]
j'ai ajouté du coup, on s'occupe du \x ou pas?

**Comment by sikorama** [comment]
et pour envoyer le \ ? \\ ? 
Je vois pas trop l'usage en asm cpc, tu as un exemple?

**Comment by EdouardBERGE** [comment]
Je n'ai même pas d'usage à proposer pour les autres ^_^
Le truc est que rasm s'ouvre de plus en plus au monde extérieur (fonctionnalités ZX mais pas que) et que certains portent des ROM du basic microsoft (par exemple) donc si rasm reste spécialisé CPC, il peut servir à tout projet Z80
